// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@crypto-sss.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/sss-access-test": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tests various access structure scenarios for the secret sharing algorithm. Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Test Access Structure Scenarios",
                "responses": {
                    "200": {
                        "description": "Access structure test results",
                        "schema": {
                            "$ref": "#/definitions/types.MessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - admin only",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/sss-healthcheck": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tests the Shamir's Secret Sharing algorithm with provided parameters. Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Test Secret Sharing Algorithm",
                "parameters": [
                    {
                        "description": "Test parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.SSSTestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSS test results",
                        "schema": {
                            "$ref": "#/definitions/types.SSSTestResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - admin only",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists all users in the system. Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by role",
                        "name": "role",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of users",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.UserResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - admin only",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/users/{id}/role": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a user's role. Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update user role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "New role (voter, auditor, official, admin)",
                        "name": "role",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated user",
                        "schema": {
                            "$ref": "#/definitions/types.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - admin only",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "Authenticates a user with username and password, returns a JWT token on success.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful login with relevant authentication response",
                        "schema": {
                            "$ref": "#/definitions/types.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid password",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalidates the user's JWT token by adding it to a blacklist until expiration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "Successful logout",
                        "schema": {
                            "$ref": "#/definitions/types.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid authorization header",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token blacklisted or invalid",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Creates a new user account with the provided username and password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User registration",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful registration with relevant authentication response",
                        "schema": {
                            "$ref": "#/definitions/types.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/validate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Validates the current JWT token and returns success if valid.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Validate token",
                "responses": {
                    "200": {
                        "description": "Token is valid",
                        "schema": {
                            "$ref": "#/definitions/types.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid authorization header",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token blacklisted or invalid",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/ballots": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Casts an encrypted vote for a poll. Only voters can cast ballots.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ballots"
                ],
                "summary": "Cast a vote",
                "parameters": [
                    {
                        "description": "Encrypted ballot",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CastBallotRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Ballot cast successfully",
                        "schema": {
                            "$ref": "#/definitions/types.BallotResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or poll not open",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Already voted or not a voter",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Poll not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/ballots/contribute-share": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Contributes a share to participate in revealing poll results. Only auditors and officials can contribute.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ballots"
                ],
                "summary": "Contribute share for reveal",
                "parameters": [
                    {
                        "description": "Share contribution",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ContributeShareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Share contributed",
                        "schema": {
                            "$ref": "#/definitions/types.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not authorized to contribute",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No share found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/ballots/poll/{poll_id}/my-ballot": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the ballot receipt for the authenticated user for a specific poll.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ballots"
                ],
                "summary": "Get my ballot receipt",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Poll ID",
                        "name": "poll_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ballot receipt",
                        "schema": {
                            "$ref": "#/definitions/types.BallotResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid poll ID",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Ballot not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/polls": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all polls. Optionally filter by status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "polls"
                ],
                "summary": "List all polls",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (draft, open, closed, frozen, revealed)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of polls",
                        "schema": {
                            "$ref": "#/definitions/types.PollListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new voting poll. Only officials and admins can create polls.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "polls"
                ],
                "summary": "Create a new poll",
                "parameters": [
                    {
                        "description": "Poll creation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreatePollRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Poll created successfully",
                        "schema": {
                            "$ref": "#/definitions/types.PollResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - insufficient permissions",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/polls/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a poll by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "polls"
                ],
                "summary": "Get a poll by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Poll ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Poll found",
                        "schema": {
                            "$ref": "#/definitions/types.PollResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid poll ID",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Poll not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/polls/{id}/freeze": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Freezes the poll, computes ballot commitment, and distributes secret shares to auditors and officials.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "polls"
                ],
                "summary": "Freeze poll and distribute shares",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Poll ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Poll frozen and shares distributed",
                        "schema": {
                            "$ref": "#/definitions/types.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or poll state",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Poll not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/polls/{id}/my-share": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the secret share assigned to the authenticated user for a specific poll.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "polls"
                ],
                "summary": "Get my share for a poll",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Poll ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Share retrieved",
                        "schema": {
                            "$ref": "#/definitions/types.ShareDistributionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid poll ID",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No share found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/polls/{id}/results": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the revealed results of a poll. Only available for revealed polls.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "polls"
                ],
                "summary": "Get poll results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Poll ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Poll results",
                        "schema": {
                            "$ref": "#/definitions/types.PollResultResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid poll ID",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Poll or results not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/polls/{id}/reveal": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Reconstructs the master key from contributed shares and decrypts ballots to reveal results.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "polls"
                ],
                "summary": "Reveal poll results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Poll ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Results revealed",
                        "schema": {
                            "$ref": "#/definitions/types.PollResultResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or insufficient shares",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Poll not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/polls/{id}/share-status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Gets the current status of share collection for revealing a poll.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "polls"
                ],
                "summary": "Get share collection status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Poll ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Share status",
                        "schema": {
                            "$ref": "#/definitions/types.ShareStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid poll ID",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Poll not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/polls/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the status of a poll. Only the creator, officials, or admins can update status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "polls"
                ],
                "summary": "Update poll status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Poll ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdatePollStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Poll status updated",
                        "schema": {
                            "$ref": "#/definitions/types.PollResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Poll not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.AccessStructureType": {
            "type": "string",
            "enum": [
                "officials_only",
                "auditors_only",
                "both"
            ],
            "x-enum-varnames": [
                "AccessStructureOfficialsOnly",
                "AccessStructureAuditorsOnly",
                "AccessStructureBoth"
            ]
        },
        "types.AccessTestResult": {
            "type": "object",
            "properties": {
                "auditor_group": {
                    "type": "string",
                    "example": "auditors"
                },
                "can_reconstruct": {
                    "type": "boolean",
                    "example": true
                },
                "message": {
                    "type": "string",
                    "example": "Access structure validated successfully"
                },
                "official_group": {
                    "type": "string",
                    "example": "officials"
                },
                "tree_structure": {
                    "type": "string",
                    "example": "AND(auditors, officials)"
                }
            }
        },
        "types.AuthResponse": {
            "type": "object",
            "properties": {
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.UserRole"
                        }
                    ],
                    "example": "voter"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "types.BallotResponse": {
            "type": "object",
            "properties": {
                "cast_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "poll_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "vote_commitment": {
                    "type": "string",
                    "example": "a1b2c3d4..."
                }
            }
        },
        "types.CastBallotRequest": {
            "type": "object",
            "required": [
                "encrypted_vote",
                "poll_id"
            ],
            "properties": {
                "encrypted_vote": {
                    "type": "string",
                    "example": "base64_encrypted_data"
                },
                "poll_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                }
            }
        },
        "types.ContributeShareRequest": {
            "type": "object",
            "required": [
                "poll_id",
                "share_value"
            ],
            "properties": {
                "poll_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "share_value": {
                    "type": "string",
                    "example": "base64_share_value"
                }
            }
        },
        "types.CreatePollRequest": {
            "type": "object",
            "required": [
                "access_structure_type",
                "options",
                "title"
            ],
            "properties": {
                "access_structure_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.AccessStructureType"
                        }
                    ],
                    "example": "both"
                },
                "description": {
                    "type": "string",
                    "example": "Annual board member election"
                },
                "end_time": {
                    "type": "string"
                },
                "min_auditors_required": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 1
                },
                "min_officials_required": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 2
                },
                "options": {
                    "type": "array",
                    "minItems": 2,
                    "items": {
                        "$ref": "#/definitions/types.PollOption"
                    }
                },
                "start_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "example": "Board Election 2024"
                }
            }
        },
        "types.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid credentials"
                }
            }
        },
        "types.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "secretpassword"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "types.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "operation successful"
                }
            }
        },
        "types.PollListResponse": {
            "type": "object",
            "properties": {
                "polls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.PollResponse"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "types.PollOption": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "option_1"
                },
                "label": {
                    "type": "string",
                    "example": "Candidate A"
                }
            }
        },
        "types.PollResponse": {
            "type": "object",
            "properties": {
                "access_structure_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.AccessStructureType"
                        }
                    ],
                    "example": "both"
                },
                "ballot_commitment": {
                    "type": "string",
                    "example": "a1b2c3d4..."
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "creator_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "description": {
                    "type": "string",
                    "example": "Annual board member election"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "min_auditors_required": {
                    "type": "integer",
                    "example": 1
                },
                "min_officials_required": {
                    "type": "integer",
                    "example": 2
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.PollOption"
                    }
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.PollStatus"
                        }
                    ],
                    "example": "open"
                },
                "title": {
                    "type": "string",
                    "example": "Board Election 2024"
                },
                "total_auditors": {
                    "type": "integer",
                    "example": 2
                },
                "total_officials": {
                    "type": "integer",
                    "example": 3
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "types.PollResultResponse": {
            "type": "object",
            "properties": {
                "poll_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "results": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "revealed_at": {
                    "type": "string",
                    "example": "2024-01-20T15:00:00Z"
                },
                "total_votes": {
                    "type": "integer",
                    "example": 150
                }
            }
        },
        "types.PollStatus": {
            "type": "string",
            "enum": [
                "draft",
                "open",
                "closed",
                "revealed"
            ],
            "x-enum-varnames": [
                "PollStatusDraft",
                "PollStatusOpen",
                "PollStatusClosed",
                "PollStatusRevealed"
            ]
        },
        "types.RegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "role",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "secretpassword"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.UserRole"
                        }
                    ],
                    "example": "voter"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "types.SSSTestRequest": {
            "type": "object",
            "required": [
                "secret",
                "threshold",
                "total"
            ],
            "properties": {
                "secret": {
                    "type": "string",
                    "example": "my_test_secret"
                },
                "threshold": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 2
                },
                "total": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 3
                }
            }
        },
        "types.SSSTestResponse": {
            "type": "object",
            "properties": {
                "access_structure_test": {
                    "$ref": "#/definitions/types.AccessTestResult"
                },
                "match": {
                    "type": "boolean",
                    "example": true
                },
                "original_secret": {
                    "type": "string",
                    "example": "my_test_secret"
                },
                "reconstructed_secret": {
                    "type": "string",
                    "example": "my_test_secret"
                },
                "share_commitments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "threshold": {
                    "type": "integer",
                    "example": 2
                },
                "total_shares": {
                    "type": "integer",
                    "example": 3
                },
                "used_share_indices": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2
                    ]
                }
            }
        },
        "types.ShareDistributionResponse": {
            "type": "object",
            "properties": {
                "commitment": {
                    "type": "string",
                    "example": "a1b2c3d4..."
                },
                "group_name": {
                    "type": "string",
                    "example": "auditors"
                },
                "poll_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "share_index": {
                    "type": "integer",
                    "example": 1
                },
                "share_value": {
                    "type": "string",
                    "example": "base64_share_value"
                }
            }
        },
        "types.ShareStatusResponse": {
            "type": "object",
            "properties": {
                "auditor_shares": {
                    "type": "integer",
                    "example": 1
                },
                "can_reveal": {
                    "type": "boolean",
                    "example": true
                },
                "contributed_by": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "min_auditors_required": {
                    "type": "integer",
                    "example": 1
                },
                "min_officials_required": {
                    "type": "integer",
                    "example": 2
                },
                "official_shares": {
                    "type": "integer",
                    "example": 2
                },
                "poll_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                }
            }
        },
        "types.UpdatePollStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.PollStatus"
                        }
                    ],
                    "example": "open"
                }
            }
        },
        "types.UserResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.UserRole"
                        }
                    ],
                    "example": "voter"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "types.UserRole": {
            "type": "string",
            "enum": [
                "voter",
                "auditor",
                "official",
                "admin"
            ],
            "x-enum-varnames": [
                "RoleVoter",
                "RoleAuditor",
                "RoleOfficial",
                "RoleAdmin"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter JWT token directly (Bearer prefix is optional).",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CRYPTO-SSS Backend API",
	Description:      "Backend API for the CRYPTO-SSS project providing authentication and secret sharing services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
